name: donation_platform
description: A platform for connecting donors with organizations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  pinput: ^2.2.21
  crypto: ^3.0.3
  
  # Core
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  supabase_flutter: ^1.10.4
  
  # UI Components
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  timeago: ^3.5.0
  
  # Storage & Security
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.2
  
  # Location Services
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.12
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  share: ^2.0.4
  connectivity_plus: ^4.0.1
  package_info_plus: ^4.0.2
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/.env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700